# Generated by Django 2.2.4 on 2020-04-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apiaap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_img',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
